name: myenv
channels:
  - conda-forge
dependencies:
  - python=3.9
  - streamlit=1.28.0
  - python-dotenv=1.0.0
  - jupyter=1.0.0
  - requests=2.31.0
  - tqdm=4.66.1
  - plotly=5.16.1
  - scikit-learn=1.3.0
  - xgboost=1.7.6
  - lightgbm=4.0.0
  - geopandas=0.14.0
  - holidays
  - pip
  - pip:
      - comet_ml
