name: hourly-subway-passenger-flow-inference-pipeline

on:
  workflow_run:
    workflows: ["hourly-subway-passenger-flow-feature-pipeline"]  
    types:
      - completed

  workflow_dispatch:

jobs:
  inference_pipeline:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.9
        activate-environment: myenv
        environment-file: environment.yml

    - name: Cache Conda packages
      uses: actions/cache@v3
      with:
        path: ~/conda_pkgs_dir
        key: conda-${{ runner.os }}-${{ hashFiles('environment.yml') }}

    - name: Install dependencies
      run: conda env update --file environment.yml --name myenv

    # Step to install Jupyter and nbconvert if it's not in environment.yml
    - name: Install Jupyter
      run: conda install jupyter nbconvert

    - name: Run Inference Pipeline Notebook
      env: 
        HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        COMET_ML_API_KEY: ${{ secrets.COMET_ML_API_KEY }}
        COMET_ML_WORKSPACE: ${{ secrets.COMET_ML_WORKSPACE }}
        COMET_ML_PROJECT_NAME: ${{ secrets.COMET_ML_PROJECT_NAME }}
      run: |
        conda run -n my-env jupyter nbconvert --to notebook --execute notebooks/inference_pipeline.ipynb
