[hopsworks]
HOPSWORKS_API_KEY="iNQnQSh5ABtEtb0O.RwH8wJf0zdpgdwjLWfBxj1LnCBpTmCjtJ7OrAS4DQQMyeEMdruNDDwK6oCUg67f7"

[comet_ml]
COMET_ML_API_KEY="sNxEfb3Vt1PiEqnGhScW4o67N"
COMET_ML_WORKSPACE="simonmontt"
COMET_ML_PROJECT_NAME="ba-passenger-flow"